spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/everyone_sprint?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: everyone_sprint_app
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6479
    password: admin1234
  mail:
    host: localhost
    port: 20000
    protocol: smtp
    username: everyone_sprint
    password: enterpr1se!
    default-encoding: UTF-8
  session:
    store-type: redis
    redis:
      cluster:
        nodes: 127.0.0.1:6479
      flush-mode: immediate # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
  messages:
    basename: messages/message
    encoding: UTF-8
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  servlet:
    multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB

file:
  upload-dir: c:/fileupload/
  allowed-extension: txt,pdf,png,jpg,gif

everyone_sprint:
  locale:
    default: ko
  corsUrls: http://localhost:5000, http://everyone-sprint.com:5000, https://everyone-sprint.com
  url: http://www.everyone-sprint.com
  web-url: http://localhost:5000/
  mail:
    senderName: noreply@everyone-sprint.com
server:
  port : 15000
  servlet:
    session:
      timeout: 6000 # Session timeout. If a duration suffix is not specified, seconds is used.

oauth:
  kakao: # https://kauth.kakao.com/oauth/authorize?client_id=1ba583809df9ceeba9305df8e05fe532&redirect_uri=http://localhost:8080/api/oauth/kakao/token&response_type=code&state=hyunseok
    host: https://kauth.kakao.com
    api-host: https://kapi.kakao.com
    token-endpoint: /oauth/token
    userinfo-endpoint: /v2/user/me
    client-id: 1ba583809df9ceeba9305df8e05fe532
    redirect-uri: http://localhost:8080/api/oauth/kakao/token
  facebook:   # https://www.facebook.com/v3.2/dialog/oauth?client_id=212487773500466&redirect_uri=http://localhost:8080/api/oauth/facebook/token&state=test&scope=email
    host: https://graph.facebook.com
    api-host: https://graph.facebook.com
    token-endpoint: /v3.2/oauth/access_token
    userinfo-endpoint: /me
    client-id: 212487773500466
    client-secret: 54a7e228616caa03c7a43805fa976b30
    redirect-uri: http://localhost:8080/api/oauth/facebook/token
  naver: # https://nid.naver.com/oauth2.0/authorize?client_id=FYKlwGmkoKaH8XSh3q6F&redirect_uri=http://localhost:8080/api/oauth/naver/token&response_type=code
    host: https://nid.naver.com
    api-host: https://openapi.naver.com
    token-endpoint: /oauth2.0/token
    userinfo-endpoint: /v1/nid/me
    client-id: FYKlwGmkoKaH8XSh3q6F
    client-secret: mTUlcxtCvQ
    redirect-uri: http://localhost:8080/api/oauth/naver/token
  google: # https://accounts.google.com/o/oauth2/v2/auth?scope=email&access_type=offline&include_granted_scopes=true&response_type=code&redirect_uri=http://localhost:8080/api/oauth/google/token&client_id=766766390358-u4v4i9huft470ol689enfi9mq3gppbs6.apps.googleusercontent.com
    host: https://accounts.google.com
    api-host: https://www.googleapis.com
    token-endpoint: /o/oauth2/token
    userinfo-endpoint: /oauth2/v2/userinfo
    client-id: 766766390358-u4v4i9huft470ol689enfi9mq3gppbs6.apps.googleusercontent.com
    client-secret: E6CJ8_bxiCfzh0r-8-44b4KV
    redirect-uri: http://localhost:8080/api/oauth/google/token

