spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/everyone_sprint?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&cacheDefaultTimezone=false
    username: everyone_sprint_app
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update #create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        type: trace
  redis:
    host: 127.0.0.1
    port: 6479
    password: admin1234
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: everyonesprint
  messages:
    basename: messages/message
    encoding: UTF-8
  servlet:
    multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB
server:
  port : 15000
  servlet:
    session:
      timeout: 12h # Session timeout. If a duration suffix is not specified, seconds is used.
  ssl:
    key-store: classpath:keystores/keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-password: a123456
    key-alias: keystore-alias
everyone_sprint:
  locale:
    default: en
  corsUrls: https://localhost:5000, https://everyone-sprint.com:5000, https://everyone-sprint.com, http://localhost:5000, http://everyone-sprint.com:5000, http://everyone-sprint.com
  url: https://www.everyone-sprint.com
  web-url: https://localhost:5000/
